apiVersion: apps/v1
kind: Deployment
metadata:
  name: apim-deployment
  namespace: apim
  labels:
    app: apim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apim-app
  template:
    metadata:
      labels:
        app: apim-app
    spec:
      containers:
      - name: apim-app
        image: wso2/wso2am:4.0.0
        ports:
        - containerPort: 8443
        - containerPort: 8280
        - containerPort: 9443
        - containerPort: 9763
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "3Gi"
            cpu: "3"
