apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apim-ingress
  namespace: apim
spec:
  tls:
  - hosts:
    - localhost
    secretName: apim-secret
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apim-service
            port:
              number: 9443
      - path: /carbon
        pathType: Prefix
        backend:
          service:
            name: apim-service
            port:
              number: 9443
      - path: /publisher
        pathType: Prefix
        backend:
          service:
            name: apim-service
            port:
              number: 9763
  ingressClassName: nginx