apiVersion: v1
kind: PersistentVolume
metadata:
  name: apim-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/d/kube/apim
  storageClassName: "hostpath"
  claimRef:
    name: apim-pvc
    namespace: apim